import LeanDb.Native.Storage
import LeanDb.Typed.Schema
import LeanDb.Model.Metadata

/-! # Native evidence for model storage

The dictionaries `native_schema%` generates for the ORIGINAL model types, indexed by the
schema: a request must carry this typed evidence; a runtime type name is insufficient. -/

namespace LeanDb.Native

/-- Native, schema-indexed dictionaries for one model entity. -/
structure EntityStorage (s T : Type) [IsSchema s] : Type 1 where
  entity : LeanDb.Entity T
  indexes : LeanDb.Indexes T
  unique : @LeanDb.HasUnique T entity
  foreignKey : @LeanDb.HasForeignKey T entity
  schema : @LeanDb.IsSchema.Has s T inferInstance entity
  pack : @LeanDb.IsSchema.HasPack s T inferInstance entity unique foreignKey schema
  referencedBy : @LeanDb.HasReferencedBy s T inferInstance
  /-- Semantic declaration identity for this EXACT typed native alternative.
      Generated instances map each alternative to its declared constraint. -/
  sourceUnique : @LeanDb.Unique T entity unique → String :=
    @LeanDb.Unique.identity T entity unique

class HasEntityStorage (s T : Type) [IsSchema s] : Type 1 where
  storage : EntityStorage s T

/-- Native evidence for one declared unique constraint (`constraint T.c : unique …`,
single-field or composite), anchored to the exact entity dictionary. It names the native
typed alternative, converts the model key to the native one, and proves both agreements:
- `identity_agrees`: the alternative's semantic identity is the declaration's, so a native
  conflict maps to exactly this `T.Conflict` constructor;
- `key_agrees`: probing the index with `encode (key.key r)` probes with the native key of
  `r`, so `findBy k` finds exactly the row whose model key is `k`.
Generated by `native_schema%` with `encode := id` and both laws by `rfl`. -/
structure UniqueStorage {s T K : Type} [IsSchema s] (storage : EntityStorage s T)
    (key : LeanDb.Model.UniqueKey T K) : Type 1 where
  index : @LeanDb.Unique T storage.entity storage.unique
  encode : K → @LeanDb.Unique.Key T storage.entity storage.unique index
  identity_agrees : storage.sourceUnique index = key.identity
  key_agrees : ∀ record : T,
    encode (key.key record) = @LeanDb.Unique.keyOf T storage.entity storage.unique index record

/-- Selects the generated evidence for one declared constraint's key, on the schema's own
entity dictionary. -/
class HasUniqueStorage (s T K : Type) [IsSchema s] [HasEntityStorage s T]
    (key : LeanDb.Model.UniqueKey T K) : Type 1 where
  lookup : UniqueStorage (HasEntityStorage.storage (s := s) (T := T)) key

/-- An ordinary entity `Edge` read as a link from `Parent` to `Target` through two of its
reference fields (`Loan.book` → `Loan.member`): the exact native `LinkRelation` over the
schema's own dictionaries. Its column laws are `rfl`, generated by `native_schema%` for every
declared `link E.parent E.target`. -/
structure LinkStorage (s Parent Target Edge : Type) [IsSchema s] : Type 1 where
  parent : EntityStorage s Parent
  target : EntityStorage s Target
  edge : EntityStorage s Edge
  relation : @LinkRelation Parent Target Edge edge.entity

/-- Selects the link of `Edge` from its `parentField` reference to its `targetField` reference. -/
class HasLinkStorage (s Edge : Type) (parentField targetField : String)
    (Parent Target : outParam Type) [IsSchema s] : Type 1 where
  storage : LinkStorage s Parent Target Edge

/-- Native evidence for a model `LinkKey` (`Loan.link.book.member`) on the edge storage: the
generated `LinkStorage`, and proof that its getters are the key's references. -/
structure LinkEvidence {s E P T : Type} [IsSchema s] (edges : EntityStorage s E)
    (key : LeanDb.Model.LinkKey E P T) : Type 1 where
  parentIdentity : Ontology.HasTypeId P
  targetIdentity : Ontology.HasTypeId T
  link : LinkStorage s P T E
  parent_agrees : ∀ edge : E,
    @LinkRelation.getParent P T E link.edge.entity link.relation edge =
      (⟨Int64.ofInt ((key.parent edge).key.toInt?.getD 0)⟩ : LeanDb.Id P)
  target_agrees : ∀ edge : E,
    @LinkRelation.getTarget P T E link.edge.entity link.relation edge =
      (⟨Int64.ofInt ((key.target edge).key.toInt?.getD 0)⟩ : LeanDb.Id T)

class HasLinkEvidence (s E P T : Type) [IsSchema s] [HasEntityStorage s E]
    (key : LeanDb.Model.LinkKey E P T) : Type 1 where
  evidence : LinkEvidence (HasEntityStorage.storage (s := s) (T := E)) key

/-- Two entity dictionaries are the same one. The only instance is reflexive, so resolving
`SameStorage a b` asks the unifier whether `b` IS `a`, at instance transparency. That is how
a request's `HasEntityResource.witness` (not reducible, so it cannot index an instance) is
matched to the schema's dictionary: no other storage gains evidence. -/
class SameStorage {s T : Type} [IsSchema s] (a b : EntityStorage s T) : Prop where
  same : a = b

instance {s T : Type} [IsSchema s] (a : EntityStorage s T) : SameStorage a a := ⟨rfl⟩

/-- A typed model path matched to one native column. Identity text alone cannot recover
`Value` or prove that the getters agree. -/
structure FieldStorage (T Value : Type) [entity : LeanDb.Entity T] : Type 1 where
  field : @LeanDb.Entity.Field T entity
  valueType : @LeanDb.Entity.fieldTy T entity field = Value
  source : Ontology.FieldPath T Value
  getter_agrees : ∀ record : T,
    (valueType ▸ @LeanDb.Entity.get T entity field record) = source.get record

class HasFieldStorage (s T : Type) (field : String) (Value : Type)
    [IsSchema s] [entityStorage : HasEntityStorage s T] : Type 1 where
  storage : @FieldStorage T Value entityStorage.storage.entity

/-- Native evidence that one column of `T` holds the field at `path`. Only fields with a
`Wire` codec get it, so a server-only value (`PasswordHash`) has none. -/
structure ColumnEvidence {s T V : Type} [IsSchema s] (storage : EntityStorage s T)
    (path : Ontology.FieldPath T V) : Type 1 where
  column : @FieldStorage T V storage.entity
  source_agrees : @FieldStorage.source T V storage.entity column = path

class HasColumnEvidence (s T V : Type) [IsSchema s] [HasEntityStorage s T]
    (path : Ontology.FieldPath T V) : Type 1 where
  evidence : ColumnEvidence (HasEntityStorage.storage (s := s) (T := T)) path

end LeanDb.Native
