import LeanDb

/- Generated by `legacy migrate freeze`. The snapshot and the raw types are
   data: do not edit them. The migration below is yours: fill its holes. -/

namespace Legacy.Migrations

namespace V0

/-- The schema at version 0: fingerprint `7882435756683641985`. -/
def schema : List LeanDb.TableSpec :=
  [
  { name := "customers", columns := #[
      { name := "name", sqlType := LeanDb.SqlType.text, nullable := false, fkTable := none },
      { name := "email", sqlType := LeanDb.SqlType.text, nullable := true, fkTable := none },
      { name := "balance", sqlType := LeanDb.SqlType.real, nullable := false, fkTable := none }
    ] },
  { name := "orders", columns := #[
      { name := "customer_id", sqlType := LeanDb.SqlType.integer, nullable := false, fkTable := some ("customers") },
      { name := "item", sqlType := LeanDb.SqlType.text, nullable := false, fkTable := none },
      { name := "qty", sqlType := LeanDb.SqlType.integer, nullable := false, fkTable := none }
    ] }
]

/-- `customers` as stored at this version (`id` excluded). -/
structure Customers where
  name : String
  email : Option String
  balance : Float
  deriving Repr, LeanDb.Entity

/-- `orders` as stored at this version (`id` excluded). -/
structure Orders where
  customer_id : Int64
  item : String
  qty : Int64
  deriving Repr, LeanDb.Entity

end V0

end Legacy.Migrations
