import LeanDb
import Legacy.Migrations.V0
import Legacy.Entities

/- Generated by `legacy migrate freeze`. The snapshot and the raw types are
   data: do not edit them. The migration below is yours: fill its holes. -/

namespace Legacy.Migrations

namespace V1

/-- The schema at version 1: fingerprint `17105251411370212804`. -/
def schema : List LeanDb.TableSpec :=
  [
  { name := "customers", columns := #[
      { name := "name", sqlType := LeanDb.SqlType.text, nullable := false, fkTable := none },
      { name := "email", sqlType := LeanDb.SqlType.text, nullable := true, fkTable := none },
      { name := "balance", sqlType := LeanDb.SqlType.real, nullable := false, fkTable := none }
    ] },
  { name := "orders", columns := #[
      { name := "customer_id", sqlType := LeanDb.SqlType.integer, nullable := false, fkTable := some ("customers") },
      { name := "item", sqlType := LeanDb.SqlType.text, nullable := false, fkTable := none },
      { name := "size", sqlType := LeanDb.SqlType.text, nullable := false, fkTable := none, enum := some (#["small", "bulk"]) }
    ] }
]

/-- `customers` as stored at this version (`id` excluded). -/
structure Customers where
  name : String
  email : Option String
  balance : Float
  deriving Repr, LeanDb.Entity

/-- `orders` as stored at this version (`id` excluded). -/
structure Orders where
  customer_id : Int64
  item : String
  size : String
  deriving Repr, LeanDb.Entity

end V1

/-- V0 → V1. The mechanical steps are diffed from the two snapshots at
    apply time; the steps below are the judgments the diff could not make.
    1 hole(s): each `sorry` is a typed transform to write. -/
def M1 : LeanDb.Migration := {
  fromFingerprint := "7882435756683641985"
  toFingerprint := "17105251411370212804"
  snapshot := V1.schema
  steps := [
    -- table "orders": new column "size" is NOT NULL with no default — existing rows have no value for it. Make it `Option`, or give it a `:= default` (existing rows take the default), or migrate by hand.
    LeanDb.Step.transformT V0.Orders Legacy.Orders fun (old : V0.Orders) => do
      -- the rule the uncarried `big_orders` view encoded: more than ten is bulk
      let item ← Legacy.OrdersItem.make old.item
      return { customer_id := ⟨old.customer_id⟩, item,
               size := if old.qty > 10 then .bulk else .small }]
}

end Legacy.Migrations
