import Lean
import LeanDb.Pred
import LeanDb.Derive

/-! # Typed schema symbols (M14)

Unique indexes are declarations. From them, and from `Ref` / child-list
fields already on the entity, LeanDB generates the typed symbols that
later writes (M14b) and reads (this milestone) mention in their types.

A table with no `unique` declaration keeps the default `Unique α := Empty`,
so `IsEmpty (Unique α)` is found automatically.
-/

namespace LeanDb

open Lean Elab Command Meta PrettyPrinter

/-- Uninhabited types. Lean 4.33 has no `IsEmpty` in Init; writes use it so
    `insertNew` is available exactly when `InsertError α` cannot occur. -/
class IsEmpty (α : Sort u) : Prop where
  false : α → False

instance : IsEmpty Empty where
  false x := nomatch x

instance : IsEmpty PEmpty.{u} where
  false x := nomatch x

@[elab_as_elim] def IsEmpty.elim {α : Sort u} [IsEmpty α] {p : α → Sort v} (a : α) : p a :=
  (IsEmpty.false a).elim

/-! ## Unique indexes -/

/-- One unique index of `α`. Constructors are generated by `unique`. -/
class HasUnique (α : Type) [Entity α] where
  Unique : Type
  Key : Unique → Type
  keyOf : (ix : Unique) → α → Key ix
  /-- Column names of the index, in declaration order. -/
  columns : Unique → Array String
  /-- Field symbols of the index, in declaration order. Used to decide
      whether a `patch` writes a column the index covers. -/
  fieldSyms : Unique → Array (Entity.Field α)
  encodeKey : (ix : Unique) → Key ix → Array Col
  /-- Equality plan for `lookup`: one `Pred.eq` per column. -/
  predOf : (ix : Unique) → Key ix → Pred [α]
  /-- Every unique index, in declaration order. -/
  all : Array Unique

/-- Empty unique-index type: a table that declared none. `IsEmpty` is found. -/
@[reducible] instance (priority := low) {α : Type} [Entity α] : HasUnique α where
  Unique := Empty
  Key := fun x => nomatch x
  keyOf := fun x _ => nomatch x
  columns := fun x => nomatch x
  fieldSyms := fun x => nomatch x
  encodeKey := fun x _ => nomatch x
  predOf := fun x _ => nomatch x
  all := #[]

abbrev Unique (α : Type) [Entity α] [HasUnique α] := HasUnique.Unique α

abbrev Unique.Key {α : Type} [Entity α] [HasUnique α] (ix : Unique α) : Type :=
  HasUnique.Key ix

def Unique.keyOf {α : Type} [Entity α] [HasUnique α] (ix : Unique α) (v : α) :
    Unique.Key ix :=
  HasUnique.keyOf ix v

def Unique.columns {α : Type} [Entity α] [HasUnique α] (ix : Unique α) : Array String :=
  HasUnique.columns ix

def Unique.fieldSyms {α : Type} [Entity α] [HasUnique α] (ix : Unique α) :
    Array (Entity.Field α) :=
  HasUnique.fieldSyms ix

def Unique.encodeKey {α : Type} [Entity α] [HasUnique α] (ix : Unique α) (k : Unique.Key ix) :
    Array Col :=
  HasUnique.encodeKey ix k

def Unique.predOf {α : Type} [Entity α] [HasUnique α] (ix : Unique α) (k : Unique.Key ix) :
    Pred [α] :=
  HasUnique.predOf ix k

def Unique.all (α : Type) [Entity α] [HasUnique α] : Array (Unique α) :=
  HasUnique.all (α := α)

/-! ## Foreign keys (from `Ref` fields) -/

class HasForeignKey (α : Type) [Entity α] where
  ForeignKey : Type
  Target : ForeignKey → Type
  /-- `Entity` instance of the referenced table. -/
  targetEntity : (fk : ForeignKey) → Entity (Target fk)
  /-- The `Ref` field. -/
  field : (fk : ForeignKey) → Entity.Field α
  /-- A `Ref β` field has type `Id β`. -/
  fieldTy_eq : (fk : ForeignKey) → Entity.fieldTy (field fk) = Id (Target fk)
  get : (fk : ForeignKey) → α → Id (Target fk)
  /-- Every foreign key, in field-declaration order. -/
  all : Array ForeignKey

@[reducible] instance (priority := low) {α : Type} [Entity α] : HasForeignKey α where
  ForeignKey := Empty
  Target := fun x => nomatch x
  targetEntity := fun x => nomatch x
  field := fun x => nomatch x
  fieldTy_eq := fun x => nomatch x
  get := fun x _ => nomatch x
  all := #[]

abbrev ForeignKey (α : Type) [Entity α] [HasForeignKey α] := HasForeignKey.ForeignKey α

abbrev ForeignKey.Target {α : Type} [Entity α] [HasForeignKey α] (fk : ForeignKey α) : Type :=
  HasForeignKey.Target fk

def ForeignKey.field {α : Type} [Entity α] [HasForeignKey α] (fk : ForeignKey α) :
    Entity.Field α :=
  HasForeignKey.field fk

def ForeignKey.get {α : Type} [Entity α] [HasForeignKey α] (fk : ForeignKey α) (v : α) :
    Id (ForeignKey.Target fk) :=
  HasForeignKey.get fk v

def ForeignKey.targetEntity {α : Type} [Entity α] [HasForeignKey α] (fk : ForeignKey α) :
    Entity (ForeignKey.Target fk) :=
  HasForeignKey.targetEntity fk

def ForeignKey.all (α : Type) [Entity α] [HasForeignKey α] : Array (ForeignKey α) :=
  HasForeignKey.all (α := α)

/-- `ON DELETE CASCADE` when true; RESTRICT (the default) otherwise. -/
def ForeignKey.cascade {α : Type} [Entity α] [HasForeignKey α] (fk : ForeignKey α) : Bool :=
  (Entity.fieldSpec (ForeignKey.field fk)).cascade

/-- The foreign-key column as a two-table `Pred.Col`, generated where
    `fieldTy` is definitionally `Id β`. -/
class JoinCol (α β : Type) [Entity α] [Entity β] where
  col : Pred.Col [α, β] (Id β) inferInstance

/-! ## Child lists -/

class HasListField (α : Type) [Entity α] where
  ListField : Type
  Elem : ListField → Type
  get : (f : ListField) → α → List (Elem f)
  /-- The child-table name (`<parent>_<field>`). -/
  table : (f : ListField) → String
  /-- Every child list, in field-declaration order. -/
  all : Array ListField

@[reducible] instance (priority := low) {α : Type} [Entity α] : HasListField α where
  ListField := Empty
  Elem := fun x => nomatch x
  get := fun x _ => nomatch x
  table := fun x => nomatch x
  all := #[]

abbrev ListField (α : Type) [Entity α] [HasListField α] := HasListField.ListField α

abbrev ListField.Elem {α : Type} [Entity α] [HasListField α] (f : ListField α) : Type :=
  HasListField.Elem f

def ListField.get {α : Type} [Entity α] [HasListField α] (f : ListField α) (v : α) :
    List (ListField.Elem f) :=
  HasListField.get f v

def ListField.table {α : Type} [Entity α] [HasListField α] (f : ListField α) : String :=
  HasListField.table f

def ListField.all (α : Type) [Entity α] [HasListField α] : Array (ListField α) :=
  HasListField.all (α := α)

/-! ## Schema marker

`schema S := T1, T2, …` generates a marker type `S` with `IsSchema S`.
Reads, queries and state are indexed by that type (`Read S α`).
Tables are `Fin nTables`, so a `DbState` can be a function
`(t : Fin nTables) → Table (pack t).ty` in `Type`.
-/

/-- One entity of a schema, packed with the instances `DbState` needs. -/
structure PackedEntity : Type 1 where
  ty : Type
  entity : Entity ty
  indexes : Indexes ty
  unique : HasUnique ty
  foreignKey : HasForeignKey ty

/-- A finite enumerated set of entity types. Generated by `schema`.
    Tables are `Fin nTables` so a `DbState` is a function
    `(t : Fin nTables) → Table (pack t).ty` in `Type`. `schema%`
    builds `Has.id` as a concrete `Fin n` (`⟨k, by decide⟩ : Fin 2`)
    so `decide` never sees the instance parameter `i.nTables`. -/
class IsSchema (s : Type) where
  nTables : Nat
  pack : Fin nTables → PackedEntity

/-- Indices of every schema table, in declaration order. -/
def IsSchema.tables {s : Type} [i : IsSchema s] : Array (Fin i.nTables) :=
  Array.ofFn (n := i.nTables) id

/-- All `TableSpec`s of the schema, parents then children, in declaration
    order — what `openDb` wants. -/
def IsSchema.specs (s : Type) [i : IsSchema s] : List TableSpec :=
  i.tables.toList.flatMap fun t =>
    let p := i.pack t
    @Entity.specs p.ty p.entity p.indexes

/-- `α` is a table of schema `s`. Generated per entity listed in `schema`. -/
class IsSchema.Has (s : Type) (α : Type) [i : IsSchema s] [Entity α] where
  id : Fin i.nTables
  ty_eq : (i.pack id).ty = α

/-! ## Inbound references, over a schema -/

class HasReferencedBy (s : Type) (α : Type) [i : IsSchema s] where
  ReferencedBy : Type
  /-- Source entity of this inbound key. -/
  Source : ReferencedBy → Type
  sourceEntity : (r : ReferencedBy) → Entity (Source r)
  /-- The `Ref` field on the source row. -/
  getFk : (r : ReferencedBy) → Source r → Id α
  /-- SQLite column name of the inbound key. -/
  columnName : ReferencedBy → String
  /-- `ON DELETE CASCADE` when true. -/
  cascade : ReferencedBy → Bool
  /-- Unfolds to a Boolean literal so `Restricting` is definitionally
      `Empty` when every inbound key cascades (or there are none). -/
  anyRestrict : Bool
  /-- Every inbound key, sources in schema order then field order. -/
  all : Array ReferencedBy
  /-- Schema-table index of the source entity. Used by `deleteCascading`
      to load that table from `DbState`. -/
  sourceId : ReferencedBy → Fin i.nTables
  /-- `(pack (sourceId r)).ty` is the source entity. -/
  sourceTy_eq : (r : ReferencedBy) → (i.pack (sourceId r)).ty = Source r

@[reducible] instance (priority := low) {s α : Type} [IsSchema s] : HasReferencedBy s α where
  ReferencedBy := Empty
  Source := fun x => nomatch x
  sourceEntity := fun x => nomatch x
  getFk := fun x _ => nomatch x
  columnName := fun x => nomatch x
  cascade := fun x => nomatch x
  anyRestrict := false
  all := #[]
  sourceId := fun x => nomatch x
  sourceTy_eq := fun x => nomatch x

abbrev ReferencedBy (s : Type) (α : Type) [IsSchema s] [HasReferencedBy s α] :=
  HasReferencedBy.ReferencedBy s α

abbrev ReferencedBy.Source {s α : Type} [IsSchema s] [HasReferencedBy s α] (r : ReferencedBy s α) : Type :=
  HasReferencedBy.Source r

def ReferencedBy.sourceEntity {s α : Type} [IsSchema s] [HasReferencedBy s α] (r : ReferencedBy s α) :
    Entity (ReferencedBy.Source r) :=
  HasReferencedBy.sourceEntity r

def ReferencedBy.getFk {s α : Type} [IsSchema s] [HasReferencedBy s α] (r : ReferencedBy s α)
    (v : ReferencedBy.Source r) : Id α :=
  HasReferencedBy.getFk r v

def ReferencedBy.columnName {s α : Type} [IsSchema s] [HasReferencedBy s α] (r : ReferencedBy s α) : String :=
  HasReferencedBy.columnName r

def ReferencedBy.sourceName {s α : Type} [IsSchema s] [HasReferencedBy s α] (r : ReferencedBy s α) : String :=
  @Entity.tableName (ReferencedBy.Source r) (ReferencedBy.sourceEntity r)

def ReferencedBy.all (s α : Type) [IsSchema s] [HasReferencedBy s α] : Array (ReferencedBy s α) :=
  HasReferencedBy.all (s := s) (α := α)

/-- `ON DELETE CASCADE` when true; RESTRICT otherwise. -/
@[reducible] def ReferencedBy.cascade {s α : Type} [IsSchema s] [HasReferencedBy s α]
    (r : ReferencedBy s α) : Bool :=
  HasReferencedBy.cascade r

/-- True when this inbound key restricts a delete of `α`. -/
@[reducible] def ReferencedBy.restricts {s α : Type} [IsSchema s] [HasReferencedBy s α]
    (r : ReferencedBy s α) : Bool :=
  !ReferencedBy.cascade r

/-- Whether any inbound key restricts a delete. -/
@[reducible] def ReferencedBy.anyRestrict (s α : Type) [IsSchema s] [HasReferencedBy s α] : Bool :=
  HasReferencedBy.anyRestrict (s := s) (α := α)

/-- Inbound keys that restrict a delete. `Empty` when every inbound key
    cascades (or there are none), so `DeleteError.restricted` is omitted. -/
@[reducible] def ReferencedBy.Restricting (s α : Type) [IsSchema s] [HasReferencedBy s α] : Type :=
  if ReferencedBy.anyRestrict s α then
    { r : ReferencedBy s α // ReferencedBy.restricts r = true }
  else
    Empty

def ReferencedBy.Restricting.val {s α : Type} [IsSchema s] [HasReferencedBy s α]
    (t : ReferencedBy.Restricting s α) : ReferencedBy s α :=
  if hAny : ReferencedBy.anyRestrict s α then
    (cast (by simp [ReferencedBy.Restricting, hAny]) t :
      { r : ReferencedBy s α // ReferencedBy.restricts r = true }).1
  else
    nomatch (cast (by simp [ReferencedBy.Restricting, hAny]) t : Empty)

def ReferencedBy.toRestricting {s α : Type} [IsSchema s] [HasReferencedBy s α]
    (r : ReferencedBy s α) (h : ReferencedBy.restricts r = true)
    (hAny : ReferencedBy.anyRestrict s α = true) : ReferencedBy.Restricting s α :=
  cast (by simp [ReferencedBy.Restricting, hAny])
    (⟨r, h⟩ : { r : ReferencedBy s α // ReferencedBy.restricts r = true })

instance {s α : Type} [IsSchema s] [h : HasReferencedBy s α] [IsEmpty h.ReferencedBy] :
    IsEmpty (ReferencedBy.Restricting s α) where
  false t :=
    if hAny : ReferencedBy.anyRestrict s α then
      IsEmpty.false
        (cast (by simp [ReferencedBy.Restricting, hAny]) t :
          { r : ReferencedBy s α // ReferencedBy.restricts r = true }).1
    else
      nomatch (cast (by simp [ReferencedBy.Restricting, hAny]) t : Empty)

/-! ## Checked values -/

/-- Every stored value of `α` satisfies this: the declared invariant, or
    `True` when the entity has none. -/
def Invariant (α : Type) [Entity α] (v : α) : Prop :=
  match Entity.invariant (α := α) with
  | none => True
  | some (_, p) => p v = true

/-- Names of the checks that failed. Today's invariant is one Bool, so a
    failure names that invariant; per-field breakdown is M14b/M9. -/
structure InvalidFields (α : Type) where
  names : List String
  deriving Repr, BEq

/-- A value that satisfies its invariant. Writes (M14b) take these. -/
def Checked (α : Type) [Entity α] := { v : α // Invariant α v }

def Checked.val {α : Type} [Entity α] (c : Checked α) : α := c.1

/-- From a proof; no runtime check. -/
def Checked.of {α : Type} [Entity α] (v : α) (h : Invariant α v) : Checked α := ⟨v, h⟩

/-- Runtime check. The sketch's `α.check`. -/
def Entity.check (α : Type) [Entity α] (v : α) : Except (InvalidFields α) (Checked α) :=
  match h : Entity.invariant (α := α) with
  | none =>
      .ok ⟨v, by unfold Invariant; rw [h]; trivial⟩
  | some (name, p) =>
      if hp : p v = true then
        .ok ⟨v, by unfold Invariant; rw [h]; exact hp⟩
      else
        .error ⟨[name]⟩

/-- `α.check v` as a projection on `Checked`. -/
def Checked.check {α : Type} [Entity α] (v : α) : Except (InvalidFields α) (Checked α) :=
  Entity.check α v

/-- A stored row whose value satisfies `Invariant`. Reads return these
    so a later write can use the proof instead of re-checking. -/
structure Valid (α : Type) [Entity α] where
  stored : Stored α
  property : Invariant α stored.val

def Valid.id {α : Type} [Entity α] (r : Valid α) : Id α := r.stored.id

def Valid.val {α : Type} [Entity α] (r : Valid α) : α := r.stored.val

def Valid.toStored {α : Type} [Entity α] (r : Valid α) : Stored α := r.stored

instance {α : Type} [Entity α] : CoeOut (Valid α) (Stored α) where
  coe := Valid.toStored

/-- `Invariant` is a Boolean equality (or `True`), so it is decidable. -/
instance {α : Type} [Entity α] (v : α) : Decidable (Invariant α v) :=
  match h : Entity.invariant (α := α) with
  | none =>
      isTrue (by unfold Invariant; rw [h]; trivial)
  | some (_, p) =>
      if hp : p v = true then
        isTrue (by unfold Invariant; rw [h]; exact hp)
      else
        isFalse (by unfold Invariant; rw [h]; exact hp)

/-- From a stored row, when the invariant holds. Runtime-free when `h`
    is a proof; `decide` closes closed goals. -/
def Valid.ofStored {α : Type} [Entity α] (r : Stored α) (h : Invariant α r.val) :
    Valid α :=
  ⟨r, h⟩

/-- Runtime wrap: `none` if the invariant fails (corruption, not a row). -/
def Valid.ofStored? {α : Type} [Entity α] (r : Stored α) : Option (Valid α) :=
  if h : Invariant α r.val then some ⟨r, h⟩ else none

/-- From `Checked` plus an assigned id. -/
def Valid.ofChecked {α : Type} [Entity α] (id : Id α) (c : Checked α) : Valid α :=
  ⟨⟨id, c.val⟩, c.property⟩

/-! ## `unique` / `schema` commands -/

structure UniqueEntry where
  typeName : Name
  ctor : Name
  fields : Array Name
  deriving Inhabited, Repr, BEq

initialize uniqueExt : EnvExtension (Array UniqueEntry) ←
  registerEnvExtension (pure #[])

private def rootIdent (n : Name) : Ident :=
  mkIdent (`_root_ ++ (privateToUserName? n).getD n)

private def resolveInNs (n : Name) : CommandElabM Name := do
  let env ← getEnv
  if env.contains n then return n
  let cand := (← getCurrNamespace) ++ n
  if env.contains cand then return cand
  throwError "unknown identifier {n}"

private def resolveEntity (n : Name) : CommandElabM Name := do
  let resolved ← resolveInNs n
  unless isStructure (← getEnv) resolved do
    throwError "{resolved} is not a structure"
  let has ← liftTermElabM do
    return (← Meta.synthInstance?
      (mkApp (mkConst ``LeanDb.Entity) (mkConst resolved))).isSome
  unless has do
    throwError "{resolved} is not an entity; `deriving LeanDb.Entity` first"
  return resolved

private def structureFieldType (typeName field : Name) : CommandElabM Expr := do
  liftTermElabM do
    let env ← getEnv
    let fields := getStructureFields env typeName
    let some i := fields.findIdx? (· == field)
      | throwError "{typeName} has no field '{field}'"
    let info ← getConstInfoCtor (← getConstInfoInduct typeName).ctors.head!
    forallTelescopeReducing info.type fun ys _ => inferType ys[i]!

private def fieldTypeStx (typeName field : Name) : CommandElabM Term := do
  let ty ← structureFieldType typeName field
  liftTermElabM <|
    withOptions (fun o => o.setBool `pp.fullNames true) (delab ty)

private def isColumnField (typeName field : Name) : CommandElabM Bool := do
  -- Child lists are not columns; unique indexes cannot name them.
  let ty ← structureFieldType typeName field
  liftTermElabM do
    let ty ← whnf ty
    match ty.getAppFn with
    | .const ``List _ =>
        -- A `List` with its own codec is a scalar; a child list is Inline.
        let elem := ty.appArg!
        let inline := (← synthInstance? (mkApp (mkConst ``LeanDb.Inline) elem)).isSome
        let codec := (← synthInstance? (mkApp (mkConst ``LeanDb.ColCodec) ty)).isSome
        return codec && !inline
    | _ =>
        return (← synthInstance? (mkApp (mkConst ``LeanDb.ColCodec) ty)).isSome

syntax uniqueKeys := ident <|> ("(" ident,+ ")")

/-- `unique% User.byName := name` or `unique% User.byKey := (actor, op, key)`.
    Accumulates; `schema%` (or `typed%`) generates `Unique` and the SQLite
    unique index. Spelled `unique%` so `unique` stays an identifier
    (`IndexSpec.unique`). -/
syntax (name := uniqueCmd) "unique% " ident " := " uniqueKeys : command

private def elabUniqueCore (nameStx : Ident) (fields : Array Name) : CommandElabM Unit := do
  let n := nameStx.getId
  let typeName ←
    if n.getPrefix.isAnonymous then
      throwErrorAt nameStx "unique: expected Type.constructor, got {n}"
    else pure n.getPrefix
  let ctor := Name.mkSimple n.getString!
  let typeName ← resolveEntity typeName
  if fields.isEmpty then
    throwError "unique: index {n} names no columns"
  for f in fields do
    let env ← getEnv
    unless (getStructureFields env typeName).contains f do
      throwError "unique: {typeName} has no field '{f}'"
    unless ← isColumnField typeName f do
      throwError "unique: {typeName}.{f} is not a stored column"
  let env ← getEnv
  let existing := uniqueExt.getState env
  if existing.any (fun e => e.typeName == typeName && e.ctor == ctor) then
    throwError "unique: {typeName}.{ctor} is already declared"
  modifyEnv (uniqueExt.modifyState · (·.push { typeName, ctor, fields }))

@[command_elab uniqueCmd]
def elabUnique : CommandElab := fun stx => do
  match stx with
  | `(unique% $n:ident := $id:ident) => elabUniqueCore n #[id.getId]
  | `(unique% $n:ident := ($ids:ident,*)) =>
      elabUniqueCore n (ids.getElems.map (·.getId))
  | _ => throwUnsupportedSyntax

private def mkProdTy (tys : Array Term) : CommandElabM Term := do
  if tys.isEmpty then `(Unit)
  else if tys.size == 1 then return tys[0]!
  else
    let mut acc := tys.back!
    for i in [0:tys.size - 1] do
      let j := tys.size - 2 - i
      acc ← `($(tys[j]!) × $acc)
    return acc

private def mkTuple (xs : Array Term) : CommandElabM Term := do
  if xs.isEmpty then `(())
  else if xs.size == 1 then return xs[0]!
  else
    let mut acc := xs.back!
    for i in [0:xs.size - 1] do
      let j := xs.size - 2 - i
      acc ← `(Prod.mk $(xs[j]!) $acc)
    return acc

private def mkTupleIdents (xs : Array (TSyntax `ident)) : CommandElabM Term := do
  let ts : Array Term ← xs.mapM fun x => `($x:ident)
  mkTuple ts

private def fieldSym (typeName field : Name) : Term :=
  mkIdent (`_root_ ++ typeName ++ `Field ++ field)

private def typeIdent (typeName : Name) : Ident :=
  rootIdent typeName

private def genUnique (typeName : Name) (entries : Array UniqueEntry) : CommandElabM Unit := do
  if entries.isEmpty then return
  let uniqName := typeName ++ `Unique
  if (← getEnv).contains uniqName then
    throwError "typed: {uniqName} already exists"
  let ctors : TSyntaxArray `Lean.Parser.Command.ctor ← entries.mapM fun e =>
    `(Lean.Parser.Command.ctor| | $(mkIdent e.ctor):ident)
  elabCommand (← `(inductive $(rootIdent uniqName):ident where $ctors* deriving DecidableEq, Repr))
  let uniqId := rootIdent uniqName
  let typeId := typeIdent typeName
  let mut keyAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  let mut keyOfAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  let mut colAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  let mut fieldAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  let mut encAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  let mut predAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  let mut ixLits : Array Term := #[]
  for e in entries do
    let ctorId := mkIdent e.ctor
    let tys ← e.fields.mapM (fieldTypeStx typeName)
    let keyTy ← mkProdTy tys
    keyAlts := keyAlts.push (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => $keyTy))
    let proj : Array Term ← e.fields.mapM fun f => `(term| v.$(mkIdent f):ident)
    let keyOfRhs ← mkTuple proj
    keyOfAlts := keyOfAlts.push
      (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident, v => $keyOfRhs))
    let colTerms : Array Term ← e.fields.mapM fun f =>
      `(LeanDb.Entity.fieldName (α := $typeId) $(fieldSym typeName f))
    colAlts := colAlts.push
      (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => #[$colTerms,*]))
    let fieldTerms : Array Term := e.fields.map fun f => fieldSym typeName f
    fieldAlts := fieldAlts.push
      (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => #[$fieldTerms,*]))
    let encBinders : Array (TSyntax `ident) :=
      e.fields.mapIdx fun i _ => mkIdent (Name.mkSimple s!"k{i}")
    let encRhs : Array Term ← encBinders.mapM fun b => `(LeanDb.toCol $b)
    let encPat ← mkTupleIdents encBinders
    encAlts := encAlts.push
      (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident, $encPat => #[$encRhs,*]))
    -- pred: AND of column = component
    let kBinders : Array (TSyntax `ident) :=
      e.fields.mapIdx fun i _ => mkIdent (Name.mkSimple s!"p{i}")
    let eqs : Array Term ← e.fields.mapIdxM fun i f => do
      let b := mkIdent (Name.mkSimple s!"p{i}")
      `(LeanDb.Pred.eq (LeanDb.Pred.Col.here ($(fieldSym typeName f))) LeanDb.EqOp.eq $b)
    let predRhs ←
      if eqs.size == 1 then pure eqs[0]!
      else
        let mut acc := eqs.back!
        for j in [0:eqs.size - 1] do
          let i := eqs.size - 2 - j
          acc ← `(LeanDb.Pred.andS $(eqs[i]!) $acc)
        pure acc
    let predPat ← mkTupleIdents kBinders
    predAlts := predAlts.push
      (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident, $predPat => $predRhs))
    let cols : Array Term := e.fields.map fun f =>
      ⟨Syntax.mkStrLit f.getString!⟩
    let tbl := LeanDb.Derive.tableNameOf typeName
    let ixName := s!"uq_{tbl}_{e.ctor.getString!}"
    let nameStx : Term := ⟨Syntax.mkStrLit ixName⟩
    ixLits := ixLits.push
      (← `(term| (⟨true, #[$cols,*], none, some $nameStx⟩ : LeanDb.IndexSpec)))
  let allLits : Array Term ← entries.mapM fun e =>
    `(term| .$(mkIdent e.ctor):ident)
  elabCommand (← `(command|
    @[reducible] instance (priority := high) : LeanDb.HasUnique $(typeId) where
      Unique := $(uniqId)
      Key := fun $keyAlts:matchAlt*
      keyOf := fun $keyOfAlts:matchAlt*
      columns := fun $colAlts:matchAlt*
      fieldSyms := fun $fieldAlts:matchAlt*
      encodeKey := fun $encAlts:matchAlt*
      predOf := fun $predAlts:matchAlt*
      all := #[$allLits,*]
  ))
  elabCommand (← `(command|
    instance (priority := high) : LeanDb.Indexes $(typeId) where
      indexes := #[$ixLits,*]
  ))

private def refTarget? (ty : Expr) : MetaM (Option Name) := do
  let ty ← whnf ty
  match ty with
  | .app fn arg =>
      let fn ← whnf fn
      match fn, arg with
      | .const n _, .const tgt _ =>
          if n == ``LeanDb.Id then return some tgt else return none
      | _, _ => return none
  | _ => return none

private def childElem? (ty : Expr) : MetaM (Option Expr) := do
  let ty ← whnf ty
  match ty.getAppFn with
  | .const ``List _ =>
      let elem := ty.appArg!
      if (← synthInstance? (mkApp (mkConst ``LeanDb.Inline) elem)).isSome then
        return some elem
      else return none
  | _ => return none

private def genForeignKey (typeName : Name) : CommandElabM Unit := do
  let fields := getStructureFields (← getEnv) typeName
  let mut fks : Array (Name × Name) := #[]
  for f in fields do
    let ty ← structureFieldType typeName f
    if let some tgt ← liftTermElabM (refTarget? ty) then
      fks := fks.push (f, tgt)
  if fks.isEmpty then return
  let fkName := typeName ++ `ForeignKey
  if (← getEnv).contains fkName then
    throwError "typed: {fkName} already exists"
  let ctors : TSyntaxArray `Lean.Parser.Command.ctor ← fks.mapM fun (f, _) =>
    `(Lean.Parser.Command.ctor| | $(mkIdent f):ident)
  elabCommand (← `(inductive $(rootIdent fkName):ident where $ctors* deriving DecidableEq, Repr))
  let fkId := rootIdent fkName
  let typeId := typeIdent typeName
  let mut tgtAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  let mut fieldAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  let mut fieldTyAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  let mut getAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  let mut entAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  for (f, tgt) in fks do
    let ctorId := mkIdent f
    tgtAlts := tgtAlts.push
      (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => $(typeIdent tgt)))
    fieldAlts := fieldAlts.push
      (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => $(fieldSym typeName f)))
    fieldTyAlts := fieldTyAlts.push
      (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => rfl))
    getAlts := getAlts.push
      (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident, v => v.$(mkIdent f):ident))
    entAlts := entAlts.push
      (← `(Lean.Parser.Term.matchAltExpr|
        | .$ctorId:ident => inferInstanceAs (LeanDb.Entity $(typeIdent tgt))))
  let allLits : Array Term ← fks.mapM fun (f, _) =>
    `(term| .$(mkIdent f):ident)
  elabCommand (← `(
    @[reducible] def $(rootIdent (fkName ++ `target)):ident : $fkId → Type
      $tgtAlts:matchAlt*
  ))
  elabCommand (← `(
    @[reducible] instance (priority := high) : LeanDb.HasForeignKey $typeId where
      ForeignKey := $fkId
      Target := $(rootIdent (fkName ++ `target))
      targetEntity $entAlts:matchAlt*
      field $fieldAlts:matchAlt*
      fieldTy_eq $fieldTyAlts:matchAlt*
      get $getAlts:matchAlt*
      all := #[$allLits,*]
  ))
  for (f, tgt) in fks do
    elabCommand (← `(
      @[reducible] instance : LeanDb.JoinCol $typeId $(typeIdent tgt) where
        col := LeanDb.Pred.Col.here (ts := [$(typeIdent tgt)]) $(fieldSym typeName f)
    ))

private def genListField (typeName : Name) : CommandElabM Unit := do
  let fields := getStructureFields (← getEnv) typeName
  let mut lists : Array (Name × Expr) := #[]
  for f in fields do
    let ty ← structureFieldType typeName f
    if let some elem ← liftTermElabM (childElem? ty) then
      lists := lists.push (f, elem)
  if lists.isEmpty then return
  let lfName := typeName ++ `ListField
  if (← getEnv).contains lfName then
    throwError "typed: {lfName} already exists"
  let ctors : TSyntaxArray `Lean.Parser.Command.ctor ← lists.mapM fun (f, _) =>
    `(Lean.Parser.Command.ctor| | $(mkIdent f):ident)
  elabCommand (← `(inductive $(rootIdent lfName):ident where $ctors* deriving DecidableEq, Repr))
  let lfId := rootIdent lfName
  let typeId := typeIdent typeName
  let tbl := LeanDb.Derive.tableNameOf typeName
  let mut elemAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  let mut getAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  let mut tableAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  for (f, elem) in lists do
    let ctorId := mkIdent f
    let elemStx ← liftTermElabM do
      withOptions (fun o => o.setBool `pp.fullNames true) (delab elem)
    elemAlts := elemAlts.push
      (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => $elemStx))
    getAlts := getAlts.push
      (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident, v => v.$(mkIdent f):ident))
    let childTbl := tbl ++ "_" ++ f.getString!
    tableAlts := tableAlts.push
      (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => $(quote childTbl)))
  let allLits : Array Term ← lists.mapM fun (f, _) =>
    `(term| .$(mkIdent f):ident)
  elabCommand (← `(
    @[reducible] instance (priority := high) : LeanDb.HasListField $typeId where
      ListField := $lfId
      Elem $elemAlts:matchAlt*
      get $getAlts:matchAlt*
      table $tableAlts:matchAlt*
      all := #[$allLits,*]
  ))

/-- If `InsertError` is in scope (the user imported `LeanDb.Typed.Write`) and
    `α` has neither unique indexes nor foreign keys, generate `IsEmpty`. -/
private def genEmptyInsertError (typeName : Name) : CommandElabM Unit := do
  let insertErrorName : Name := .str (.str .anonymous "LeanDb") "InsertError"
  unless (← getEnv).contains insertErrorName do return
  let hasU := (← getEnv).contains (typeName ++ `Unique)
  let hasF := (← getEnv).contains (typeName ++ `ForeignKey)
  if hasU || hasF then return
  let ty := typeIdent typeName
  let errId := mkCIdent insertErrorName
  let emptyId := mkCIdent ``IsEmpty
  elabCommand (← `(
    instance : $emptyId ($errId $ty) where
      false e := nomatch e
  ))

/-- Generate `Unique` / `ForeignKey` / `ListField` for one entity from
    accumulated `unique` declarations and the structure's fields. -/
syntax (name := typedCmd) "typed% " ident : command

@[command_elab typedCmd]
def elabTyped : CommandElab := fun stx => do
  let typeName ← resolveEntity stx[1].getId
  let entries := (uniqueExt.getState (← getEnv)).filter (·.typeName == typeName)
  genUnique typeName entries
  genForeignKey typeName
  genListField typeName
  genEmptyInsertError typeName

private def ctorOfType (typeName : Name) : Name :=
  Name.mkSimple typeName.getString!.toLower

syntax (name := schemaCmd) "schema% " ident " := " ident,+ : command

@[command_elab schemaCmd]
def elabSchema : CommandElab := fun stx => do
  let `(schema% $s:ident := $ts:ident,*) := stx
    | throwUnsupportedSyntax
  let schemaName := (← getCurrNamespace) ++ s.getId
  if (← getEnv).contains schemaName then
    throwError "schema: {schemaName} already exists"
  let mut types : Array Name := #[]
  for idStx in ts.getElems do
    let n ← resolveEntity idStx.getId
    if types.contains n then
      throwError "schema: {n} is listed twice"
    types := types.push n
  -- Finish typed symbols per entity (Unique + Indexes, FKs, lists).
  for t in types do
    let entries := (uniqueExt.getState (← getEnv)).filter (·.typeName == t)
    unless (← getEnv).contains (t ++ `Unique) do
      genUnique t entries
    unless (← getEnv).contains (t ++ `ForeignKey) do
      genForeignKey t
    unless (← getEnv).contains (t ++ `ListField) do
      genListField t
    genEmptyInsertError t
  -- Marker type and `IsSchema` instance (`Fin n` table index).
  elabCommand (← `(structure $(rootIdent schemaName):ident where deriving Repr))
  let schemaId := rootIdent schemaName
  let n := types.size
  let mut packAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
  for hi in [0:n] do
    let t := types[hi]!
    let iLit : Term := quote hi
    packAlts := packAlts.push (← `(Lean.Parser.Term.matchAltExpr|
      | ⟨$iLit, _⟩ =>
          { ty := $(typeIdent t)
            entity := inferInstanceAs (LeanDb.Entity $(typeIdent t))
            indexes := inferInstanceAs (LeanDb.Indexes $(typeIdent t))
            unique := inferInstanceAs (LeanDb.HasUnique $(typeIdent t))
            foreignKey := inferInstanceAs (LeanDb.HasForeignKey $(typeIdent t)) }))
  -- Named instance so `Has.id` is `Fin inst.nTables` (`Fin 2`), not
  -- `Fin i.nTables` for a free instance parameter.
  let instName := schemaName ++ `instIsSchema
  let instId := rootIdent instName
  if n == 0 then
    elabCommand (← `(
      @[reducible] def $instId:ident : LeanDb.IsSchema $schemaId where
        nTables := 0
        pack x := nomatch x
    ))
  else
    elabCommand (← `(
      @[reducible] def $instId:ident : LeanDb.IsSchema $schemaId where
        nTables := $(quote n)
        pack $packAlts:matchAlt*
    ))
  elabCommand (← `(
    @[reducible] instance : LeanDb.IsSchema $schemaId := $instId:ident
  ))
  for hi in [0:n] do
    let t := types[hi]!
    let iLit : Term := quote hi
    elabCommand (← `(
      @[reducible] instance : @LeanDb.IsSchema.Has $schemaId $(typeIdent t) $instId inferInstance where
        id := ⟨$iLit, by decide⟩
        ty_eq := rfl
    ))
  -- ReferencedBy: inbound FKs, per target in the schema.
  for tgt in types do
    let mut inbound : Array (Name × Name) := #[]
    for src in types do
      let fields := getStructureFields (← getEnv) src
      for f in fields do
        let ty ← structureFieldType src f
        if let some t ← liftTermElabM (refTarget? ty) then
          if t == tgt then inbound := inbound.push (src, f)
    if inbound.isEmpty then continue
    let rbName := schemaName ++ `ReferencedBy ++ Name.mkSimple tgt.getString!
    let ctors : TSyntaxArray `Lean.Parser.Command.ctor ← inbound.mapM fun (src, f) =>
      let n := Name.mkSimple (src.getString!.toLower ++ "_" ++ f.getString!)
      `(Lean.Parser.Command.ctor| | $(mkIdent n):ident)
    elabCommand (← `(
      inductive $(rootIdent rbName):ident where $ctors* deriving DecidableEq, Repr
    ))
    let rbId := rootIdent rbName
    let mut srcAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
    let mut entAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
    let mut getAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
    let mut colAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
    let mut cascadeAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
    let mut sourceIdAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
    let mut sourceTyAlts : Array (TSyntax ``Lean.Parser.Term.matchAltExpr) := #[]
    let mut allLits : Array Term := #[]
    let env ← getEnv
    for (src, f) in inbound do
      let ctor := Name.mkSimple (src.getString!.toLower ++ "_" ++ f.getString!)
      let ctorId := mkIdent ctor
      srcAlts := srcAlts.push
        (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => $(typeIdent src)))
      entAlts := entAlts.push
        (← `(Lean.Parser.Term.matchAltExpr|
          | .$ctorId:ident => inferInstanceAs (LeanDb.Entity $(typeIdent src))))
      getAlts := getAlts.push
        (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident, v => v.$(mkIdent f):ident))
      colAlts := colAlts.push
        (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => $(quote f.getString!)))
      let casc := (LeanDb.Derive.cascadeExt.getState env).any fun e =>
        e.typeName == src && e.field == f
      cascadeAlts := cascadeAlts.push
        (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => $(quote casc)))
      let srcIdx := types.findIdx? (· == src) |>.getD 0
      let srcLit : Term := quote srcIdx
      sourceIdAlts := sourceIdAlts.push
        (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => ⟨$srcLit, by decide⟩))
      sourceTyAlts := sourceTyAlts.push
        (← `(Lean.Parser.Term.matchAltExpr| | .$ctorId:ident => rfl))
      allLits := allLits.push (← `(term| .$ctorId:ident))
    let anyR := inbound.any fun (src, f) =>
      !(LeanDb.Derive.cascadeExt.getState env).any fun e =>
        e.typeName == src && e.field == f
    elabCommand (← `(
      @[reducible] def $(rootIdent (rbName ++ `source)):ident : $rbId → Type
        $srcAlts:matchAlt*
    ))
    elabCommand (← `(
      @[reducible] instance (priority := high) :
          @LeanDb.HasReferencedBy $schemaId $(typeIdent tgt) $instId where
        ReferencedBy := $rbId
        Source := $(rootIdent (rbName ++ `source))
        sourceEntity $entAlts:matchAlt*
        getFk $getAlts:matchAlt*
        columnName $colAlts:matchAlt*
        cascade $cascadeAlts:matchAlt*
        anyRestrict := $(quote anyR)
        all := #[$allLits,*]
        sourceId $sourceIdAlts:matchAlt*
        sourceTy_eq $sourceTyAlts:matchAlt*
    ))

end LeanDb
