import LeanDbDomain.Storage
import LeanDb.Typed.Schema
import LeanApp.Domain.Metadata

namespace LeanDb.Domain

/-- Native, schema-indexed dictionaries for the ORIGINAL portable type. A
    request must carry this typed evidence; a runtime TypeId is insufficient.
    No universal codec law is asserted for unrestricted portable references. -/
structure EntityStorage (s T : Type) [IsSchema s] : Type 1 where
  entity : LeanDb.Entity T
  indexes : LeanDb.Indexes T
  unique : @LeanDb.HasUnique T entity
  foreignKey : @LeanDb.HasForeignKey T entity
  schema : @LeanDb.IsSchema.Has s T inferInstance entity
  pack : @LeanDb.IsSchema.HasPack s T inferInstance entity unique foreignKey schema
  referencedBy : @LeanDb.HasReferencedBy s T inferInstance
  /-- Semantic declaration identity for this EXACT typed native alternative.
      Generated bridge instances override the legacy native identity default. -/
  sourceUnique : @LeanDb.Unique T entity unique → String :=
    @LeanDb.Unique.identity T entity unique

class HasEntityStorage (s T : Type) [IsSchema s] : Type 1 where
  storage : EntityStorage s T

/-- Native evidence for one declared unique constraint (`constraint T.c : unique …`,
    single-field or composite), anchored to the exact entity dictionary. It names
    the native typed alternative, converts the portable key to the native one, and
    proves both agreements:
    - `identity_agrees`: the alternative's semantic identity is the declaration's,
      so a native conflict maps to exactly this `T.Conflict` constructor;
    - `key_agrees`: probing the index with `encode (key.key r)` probes with the
      native key of `r`, so `findBy k` finds exactly the row whose portable key is `k`.
    Generated by `native_schema%` with `encode := id` and both laws by `rfl`. -/
structure UniqueStorage {s T K : Type} [IsSchema s] (storage : EntityStorage s T)
    (key : LeanApp.Domain.UniqueKey T K) : Type 1 where
  index : @LeanDb.Unique T storage.entity storage.unique
  encode : K → @LeanDb.Unique.Key T storage.entity storage.unique index
  identity_agrees : storage.sourceUnique index = key.identity
  key_agrees : ∀ record : T,
    encode (key.key record) = @LeanDb.Unique.keyOf T storage.entity storage.unique index record

/-- Selects the generated evidence for one declared constraint's key, on the
    schema's own entity dictionary. -/
class HasUniqueStorage (s T K : Type) [IsSchema s] [HasEntityStorage s T]
    (key : LeanApp.Domain.UniqueKey T K) : Type 1 where
  lookup : UniqueStorage (HasEntityStorage.storage (s := s) (T := T)) key

/-- An ordinary entity `Edge` read as a link from `Parent` to `Target` through
    two of its reference fields (`Loan.book` → `Loan.member`): the exact native
    `LinkRelation` over the schema's own dictionaries. Its column laws are `rfl`,
    generated by `native_schema%` for every declared `link E.parent E.target`. -/
structure LinkStorage (s Parent Target Edge : Type) [IsSchema s] : Type 1 where
  parent : EntityStorage s Parent
  target : EntityStorage s Target
  edge : EntityStorage s Edge
  relation : @LinkRelation Parent Target Edge edge.entity

/-- Selects the link of `Edge` from its `parentField` reference to its
    `targetField` reference. -/
class HasLinkStorage (s Edge : Type) (parentField targetField : String)
    (Parent Target : outParam Type) [IsSchema s] : Type 1 where
  storage : LinkStorage s Parent Target Edge

/-- Native evidence for a portable `LinkKey` (`Loan.link.book.member`) on the edge
    storage: the generated `LinkStorage`, and proof that its getters are the key's
    references. Generated by `native_schema%` for every generated `LinkKey`. -/
structure LinkEvidence {s E P T : Type} [IsSchema s] (edges : EntityStorage s E)
    (key : LeanApp.Domain.LinkKey E P T) : Type 1 where
  parentIdentity : Ontology.HasTypeId P
  targetIdentity : Ontology.HasTypeId T
  link : LinkStorage s P T E
  parent_agrees : ∀ edge : E,
    @LinkRelation.getParent P T E link.edge.entity link.relation edge =
      (⟨Int64.ofInt ((key.parent edge).key.toInt?.getD 0)⟩ : LeanDb.Id P)
  target_agrees : ∀ edge : E,
    @LinkRelation.getTarget P T E link.edge.entity link.relation edge =
      (⟨Int64.ofInt ((key.target edge).key.toInt?.getD 0)⟩ : LeanDb.Id T)

class HasLinkEvidence (s E P T : Type) [IsSchema s] [HasEntityStorage s E]
    (key : LeanApp.Domain.LinkKey E P T) : Type 1 where
  evidence : LinkEvidence (HasEntityStorage.storage (s := s) (T := E)) key

/-- Two entity dictionaries are the same one. The only instance is reflexive, so
    resolving `SameStorage a b` asks the unifier whether `b` IS `a`, at instance
    transparency. That is how a request's `HasEntityResource.witness` (not
    reducible, so it cannot index an instance) is matched to the schema's
    dictionary: no other storage gains evidence. -/
class SameStorage {s T : Type} [IsSchema s] (a b : EntityStorage s T) : Prop where
  same : a = b

instance {s T : Type} [IsSchema s] (a : EntityStorage s T) : SameStorage a a := ⟨rfl⟩

/-- Existential relationship evidence retains the actual Edge and each coherent
    dictionary. Portable/native lowering can use it without a string cast or an
    application-owned relationship record. Source identifies one declared field. -/
structure MemberStorage (s Parent Target : Type) [IsSchema s] : Type 1 where
  parentIdentity : Ontology.HasTypeId Parent
  targetIdentity : Ontology.HasTypeId Target
  parent : EntityStorage s Parent
  target : EntityStorage s Target
  Edge : Type
  edge : EntityStorage s Edge
  relation : @MemberRelation Parent Target Edge parent.entity target.entity edge.entity
    edge.unique edge.foreignKey

class HasMemberStorage (s Parent : Type) (field : String) (Target : Type)
    [IsSchema s] : Type 1 where
  storage : MemberStorage s Parent Target

/-- A typed original-domain path matched to one native column. Identity text
    alone cannot recover Value or prove that the getters agree. -/
structure FieldStorage (T Value : Type) [entity : LeanDb.Entity T] : Type 1 where
  field : @LeanDb.Entity.Field T entity
  valueType : @LeanDb.Entity.fieldTy T entity field = Value
  source : Ontology.FieldPath T Value
  getter_agrees : ∀ record : T,
    (valueType ▸ @LeanDb.Entity.get T entity field record) = source.get record

class HasFieldStorage (s T : Type) (field : String) (Value : Type)
    [IsSchema s] [entityStorage : HasEntityStorage s T] : Type 1 where
  storage : @FieldStorage T Value entityStorage.storage.entity

/-- Generated field evidence for one exact entity dictionary and editable path.
    Dependent dictionaries are outputs of lookup, then checked against the
    dictionaries already carried by the request; their equality is not erased. -/
class HasFieldProjection (s T : Type) (field : String) (Value : outParam Type) [IsSchema s]
    (target : outParam (EntityStorage s T)) : Type 1 where
  editable : LeanApp.Domain.EditableField T field Value
  column : @FieldStorage T Value target.entity
  source_agrees : @FieldStorage.source T Value target.entity column =
    (@LeanApp.Domain.EditableField.lens T field Value editable).toFieldPath

/-- Evidence consumed by the shared projection algebra. Both the column and its
    value-type/getter laws use relation.target.entity; arbitrary sibling storage
    dictionaries cannot be substituted. -/
structure ProjectionStorage {s Parent Target Value : Type} [IsSchema s]
    (relation : MemberStorage s Parent Target) (path : Ontology.FieldPath Target Value) : Type 1 where
  column : @FieldStorage Target Value relation.target.entity
  source_agrees : @FieldStorage.source Target Value relation.target.entity column = path

theorem ProjectionStorage.getter_agrees {s Parent Target Value : Type} [IsSchema s]
    {relation : MemberStorage s Parent Target} {path : Ontology.FieldPath Target Value}
    (selection : ProjectionStorage relation path) (record : Target) :
    (@FieldStorage.valueType Target Value relation.target.entity selection.column ▸
      @LeanDb.Entity.get Target relation.target.entity
        (@FieldStorage.field Target Value relation.target.entity selection.column) record) = path.get record := by
  exact (@FieldStorage.getter_agrees Target Value relation.target.entity selection.column record).trans
    (congrArg (fun field => field.get record) selection.source_agrees)

/-- Privileged native field projection. A protected interpreter must call this
    only through its policy-first path; SQL selects this ONE proven column. -/
def FieldStorage.project {s p t e Value} [IsSchema s]
    [Entity p] [Entity t] [Entity e] [HasUnique e] [HasForeignKey e]
    [IsSchema.Has s e] [IsSchema.Has s t] (column : FieldStorage t Value)
    (relation : MemberRelation p t e) (parent : Id p) : Read s (List Value) := do
  let values ← Read.memberField relation parent column.field
  return column.valueType ▸ values

/-- Native evidence that one column of `T` holds the field at `path`. Only fields
    with a `Wire` codec get it, so a server-only value (`PasswordHash`) has none. -/
structure ColumnEvidence {s T V : Type} [IsSchema s] (storage : EntityStorage s T)
    (path : Ontology.FieldPath T V) : Type 1 where
  column : @FieldStorage T V storage.entity
  source_agrees : @FieldStorage.source T V storage.entity column = path

class HasColumnEvidence (s T V : Type) [IsSchema s] [HasEntityStorage s T]
    (path : Ontology.FieldPath T V) : Type 1 where
  evidence : ColumnEvidence (HasEntityStorage.storage (s := s) (T := T)) path

end LeanDb.Domain
