import LeanDb.Model.Request
import Lean.Elab.Term

/-! # `DB` and `Query`

`DB α` is a read-write storage program, `Query α` a read-only one: `Program` at the portable
family (`portableStorage`) and the model transaction index `OpScope`. A `Query` lifts into
`DB`; a `DB` step never lifts into `Query`. Neither fails in a domain channel: declared unique
conflicts are values (`Except T.Conflict _`), anything else is the backend's fault.

The generated entity operations (`T.insert`, `T.find`, …, see `LeanDb.Model.Entities`) call
the generic steps below. To run a `DB`/`Query` definition on a backend with real evidence
(SQLite), generalize it with `storage_requirements` (`LeanDb.Model.Requirements`). -/

namespace LeanDb.Model
open Ontology

/-- A read-write storage step. It cannot fail in the domain channel: declared unique
conflicts are values (`Except T.Conflict _`), other failures are the backend's. -/
def DB (α : Type) : Type 1 := Program portableStorage .command OpScope α
/-- A read-only storage step over one snapshot. Lifts into `DB`. -/
def Query (α : Type) : Type 1 := Program portableStorage .query OpScope α

instance : Monad DB := inferInstanceAs (Monad (Program portableStorage .command OpScope))
instance : Monad Query := inferInstanceAs (Monad (Program portableStorage .query OpScope))

instance : MonadLift Query DB := ⟨Program.toCommand⟩

/-- A larger monad that performs portable storage requests embeds `DB` (e.g. an operation
monad: `instance : MonadStorage portableStorage .command OpScope (Op ε)`). -/
instance {m : Type → Type u} [Monad m] [MonadStorage portableStorage .command OpScope m] : MonadLift DB m :=
  ⟨fun program => Program.lift (resources := portableStorage) (access := .command) (Scope := OpScope) program⟩
instance {m : Type → Type u} [Monad m] [MonadStorage portableStorage .query OpScope m] : MonadLift Query m :=
  ⟨fun program => Program.lift (resources := portableStorage) (access := .query) (Scope := OpScope) program⟩

instance : Inhabited (DB Unit) := ⟨Program.pure ()⟩
instance : Inhabited (Query Unit) := ⟨Program.pure ()⟩

/-- Per-entity row view (`T.Row Scope` extends `T` with its `id`), generated by
`deriving Entity`. `Row T` in authored code elaborates to it, so `p.date`/`p.id` work. -/
class HasRow (T : Type) (R : outParam (Type → Type)) where
  ofRow : {Scope : Type} → Row Scope T → R Scope
  toRow : {Scope : Type} → R Scope → Row Scope T

/-- Marker for `deriving Changes` / `deriving instance Changes (except := [fields]) for T`:
generates `T.Changes`, the editable fields of entity `T` (a wire record), its lawful patch
`T.Changes.toChange`, and `T.patch`. -/
class Changes (T : Type) : Type where

/-! ## Generic storage steps (portable family). Generated `T.insert`/`T.find`/… call these. -/

namespace DB
def insert [Entity T] [HasEntityResource portableStorage T] (value : T) (conflicts : List (Constraint C)) :
    DB (Except C (Ref T)) :=
  Program.request (.insert HasEntityResource.witness value conflicts)
def insertTotal [Entity T] [HasEntityResource portableStorage T] (value : T) : DB (Ref T) :=
  Program.bind (Program.request (.insert HasEntityResource.witness value ([] : List (Constraint Empty)))) fun
    | .ok id => Program.pure id
    | .error error => nomatch error
def update [Entity T] [HasEntityResource portableStorage T] [HasRow T R] (row : R OpScope) (value : T)
    (conflicts : List (Constraint C)) : DB (Except C Unit) :=
  Program.request (.update HasEntityResource.witness (HasRow.toRow (T := T) row) (Change.replace value) conflicts)
def updateTotal [Entity T] [HasEntityResource portableStorage T] [HasRow T R] (row : R OpScope) (value : T) : DB Unit :=
  Program.bind (Program.request (.update HasEntityResource.witness (HasRow.toRow (T := T) row) (Change.replace value)
    ([] : List (Constraint Empty)))) fun
    | .ok () => Program.pure ()
    | .error error => nomatch error
/-- A selective update built from lawful field lenses (`T.Changes.toChange`). Only constraints
over the changed fields can conflict; pass exactly those. -/
def patch [Entity T] [HasEntityResource portableStorage T] [HasRow T R] (row : R OpScope) (edit : Change T)
    (conflicts : List (Constraint C)) : DB (Except C Unit) :=
  Program.request (.update HasEntityResource.witness (HasRow.toRow (T := T) row) edit conflicts)
def patchTotal [Entity T] [HasEntityResource portableStorage T] [HasRow T R] (row : R OpScope) (edit : Change T) : DB Unit :=
  Program.bind (Program.request (.update HasEntityResource.witness (HasRow.toRow (T := T) row) edit
    ([] : List (Constraint Empty)))) fun
    | .ok () => Program.pure ()
    | .error error => nomatch error
def delete [Entity T] [HasEntityResource portableStorage T] [HasRow T R] (row : R OpScope) : DB Unit :=
  Program.request (.delete HasEntityResource.witness (HasRow.toRow (T := T) row))
end DB

namespace Query
def «find» [Entity T] [HasEntityResource portableStorage T] [HasRow T R] (id : Ref T) : Query (Option (R OpScope)) :=
  Program.bind (Program.request (.find HasEntityResource.witness id)) fun row => Program.pure (row.map HasRow.ofRow)
def findBy [Entity T] [storage : HasEntityResource portableStorage T] [HasRow T R] (unique : UniqueKey T K)
    [HasUniqueResource portableStorage T K storage.witness unique] (key : K) : Query (Option (R OpScope)) :=
  Program.bind (Program.request (.findBy storage.witness unique HasUniqueResource.witness key)) fun row =>
    Program.pure (row.map HasRow.ofRow)
def select [Entity T] [HasEntityResource portableStorage T] [HasRow T R] : Query (List (R OpScope)) :=
  Program.bind (Program.request (.select HasEntityResource.witness)) fun rows =>
    Program.pure (rows.map (HasRow.ofRow (T := T)))
/-- Field `field` of every `T` linked to `parent` through edge `E`, once each, by target id.
A row view of the edge or the target never reaches the caller: only the selected values. -/
def linkField [Entity E] [edges : HasEntityResource portableStorage E] [Entity T]
    [targets : HasEntityResource portableStorage T] (key : LinkKey E P T)
    [HasLinkResource portableStorage E P T edges.witness key] (field : FieldPath T V)
    [HasColumnResource portableStorage T V targets.witness field] (parent : Ref P) : Query (List V) :=
  Program.request (.linkField edges.witness key HasLinkResource.witness targets.witness field
    HasColumnResource.witness parent)
end Query

/-! ## Authored surface syntax (scoped: active with `open LeanDb.Model`) -/

/-- `Row T` is the entity's row view; `Row Scope T` the plain row in transaction `Scope`. -/
scoped syntax (name := rowType) "Row " term:max (ppSpace colGt term:max)? : term

open Lean Elab Term Meta in
elab_rules : term
  | `(rowType| Row $scope:term $target:term) => do
    elabTerm (← `(LeanDb.Model.Row $scope $target)) none
  | `(rowType| Row $target:term) => do
    let ty ← elabType target
    let rowView ← mkFreshExprMVar (some (.forallE `Scope (.sort 1) (.sort 1) .default))
    match ← synthInstance? (mkApp2 (mkConst ``HasRow) ty rowView) with
    | some _ => return mkApp (← instantiateMVars rowView) (mkConst ``OpScope)
    | none => return mkApp2 (mkConst ``LeanDb.Model.Row) (mkConst ``OpScope) ty

@[app_unexpander LeanDb.Model.Row] def unexpandRow : Lean.PrettyPrinter.Unexpander
  | `($_ $scope:ident $t) => if scope.getId.getString! == "OpScope" then `(Row $t) else `(Row $scope $t)
  | `($_ $scope $t) => `(Row $scope $t)
  | _ => throw ()

end LeanDb.Model
